runtime: python37
env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: itisnt4u
  CLOUD_SQL_DATABASE_NAME: agentebitcoin
  CLOUD_SQL_CONNECTION_NAME: agentebitcoin:southamerica-east1:agentebitcoin
  EMAIL_API_KEY: qBuXeCEQRAa2j5dMtUSWlw